# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
  #    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 2 1,7 *'
  push:
       paths:
       - 'code/set_control_params.R'
       - 'code/gen_pred_grid.R'

name: R-make-grid

jobs:
  gen-grid:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      #- name: Install gdal
        #run: |
        #sudo port install gdal
      - name: Install packages
        run:
          Rscript -e "install.packages(c('dplyr', 'lubridate', 'remotes', 'sp', 'sessioninfo'))"
      - name: Install dependencies # see https://github.com/r-spatial/sf/issues/1566
        run: |
          remotes::install_deps(dependencies = TRUE, type="binary")
        shell: Rscript {0}
       shell: Rscript {0}
      - name: Create prediction grid
        run:
          Rscript -e "source('code/gen_pred_grid.R')"
      - name: Commit results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff-index --quiet HEAD || (git commit -a -m'[bot] update files' --allow-empty && git push -f)
      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
